---
title: "web_scraping"
output: html_document
---

Include all of the libraries we will need.
```{r, results='hide', message=FALSE}
include <- function(library_name){
  if( !(library_name %in% installed.packages()) )
    install.packages(library_name) 
  library(library_name, character.only=TRUE)
}
include("rvest")
include("tidyr")
```

create a function that will take in a url and return a nibble with the semester, year, class number, section, title, and enrollment.
```{r}
read_class_schedule <- function(url) {
  schedule_html <- read_html(url)
  if (grepl("spr", url)) {
    semester <- "Spring"
  } else if (grepl("fa", url)) {
    semester <- "Fall"
  }
  year <- as.numeric(gsub('.*([0-9]{4}).*','\\1', url))
  classes <- schedule_html %>% html_nodes("tbody")

  class_subj <- classes %>% html_nodes("td.subj") %>% html_text()
  cat_num <- classes %>% html_nodes("td.cat_num") %>% html_text()
  class_num <- paste(class_subj, cat_num, sep=" ")
  
  section <- classes %>% html_nodes("td.sect") %>% html_text()
  title <- classes %>% html_nodes("td.title") %>% html_text()
  instructors <- classes %>% html_nodes("td.Instructor") %>% html_text()
  enroll <- classes %>% html_nodes("td.enrtot") %>% html_text()
  
  schedule <- tibble(semester=semester, year=year, class_number=class_num, section_number=section, course_title=title, enrollment=enroll)
  return(schedule)
}
```

Use the above function to create tables for the 2019 and 2020 CSCI and MATH classes.
```{r}
cscis2019 <- read_class_schedule("http://ems.csuchico.edu/APSS/schedule/spr2019/CSCI.shtml")
cscis2020 <- read_class_schedule("http://ems.csuchico.edu/APSS/schedule/spr2020/CSCI.shtml")
maths2019 <- read_class_schedule("http://ems.csuchico.edu/APSS/schedule/spr2019/MATH.shtml")
maths2020 <- read_class_schedule("http://ems.csuchico.edu/APSS/schedule/spr2020/MATH.shtml")
```

Combine all of the above tables into a single table.
```{r}
all_tables <- rbind(cscis2019, cscis2020, maths2019, maths2020)
```